### ISSUE TITLE
A large number of dependencies when installing module

### ISSUE THREAD

**Issue by etsoro** [ArielOnoriaga/vue-hicons#2]
When run command `yarn add vue-hicons` or `npm i -s vue-hicons@latest`, a huge number of apparently unnecessary dependencies are installed.

Problem appears both in existing projects and in a clean install in a new project.

Yarn version: 1.22.10
NPM version: 6.14.6

`yarn add v1.22.10`
`[1/4] 🔍  Resolving packages...`
`[2/4] 🚚  Fetching packages...`
`[3/4] 🔗  Linking dependencies...`
`warning " > sass-loader@8.0.2" has unmet peer dependency "webpack@^4.36.0 || ^5.0.0".`
`warning Workspaces can only be enabled in private projects.`
`[4/4] 🔨  Building fresh packages...`
`success Saved lockfile.`
`warning Workspaces can only be enabled in private projects.`
`success Saved 312 new dependencies.`
`info Direct dependencies`
`└─ vue-hicons@1.2.5`
`info All dependencies`
`├─ @akryum/winattr@3.0.0`
`├─ @apollo/protobufjs@1.0.5`
`├─ @babel/plugin-proposal-optional-chaining@7.12.7`
`├─ @babel/preset-env@7.12.7`
`├─ @endemolshinegroup/cosmiconfig-typescript-loader@1.0.2`
`├─ @fullhuman/postcss-purgecss@2.3.0`
`├─ @nodelib/fs.scandir@2.1.3`
`├─ @nodelib/fs.stat@2.0.3`
`├─ @nodelib/fs.walk@1.2.4`
`...`
`├─ vue-cli-plugin-apollo@0.21.3`
`├─ vue-codemod@0.0.4`
`├─ vue-hicons@1.2.5`
`├─ watch@1.0.2`
`├─ widest-line@2.0.1`
`├─ write-file-atomic@2.4.3`
`├─ xml2js@0.4.23`
`├─ xmlbuilder@11.0.1`
`├─ xss@1.0.8`
`├─ yaml-front-matter@3.4.1`
`├─ yarn@1.22.10`
`├─ yauzl@2.10.0`
`├─ yn@3.1.1`
`└─ zen-observable-ts@0.8.21`
`✨  Done in 25.04s.`

**Comment by ArielOnoriaga** [comment]
Thx, fixed!
